CC = g++
CFLAGS = -g -Wall

ask3:	main.cpp Object_and_PlaneComponent.cpp Employee.cpp Plane.cpp gets.cpp Mystring.cpp clone_encrypt_and_print.cpp
		$(CC) $(CFLAGS) -o askisi3 main.cpp Object_and_PlaneComponent.cpp Employee.cpp Plane.cpp gets.cpp Mystring.cpp clone_encrypt_and_print.cpp

.PHONY: clean

clean:
	rm -f askisi3
